//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.locStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages with CTC.
        /// </summary>
        internal static string CHK_Messages_MessagesWithCTC {
            get {
                return ResourceManager.GetString("CHK_Messages_MessagesWithCTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages with Errors.
        /// </summary>
        internal static string CHK_Messages_MessagesWithErrors {
            get {
                return ResourceManager.GetString("CHK_Messages_MessagesWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string CMD_Messages_List {
            get {
                return ResourceManager.GetString("CMD_Messages_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Messages.
        /// </summary>
        internal static string CMD_Messages_RefreshMessages {
            get {
                return ResourceManager.GetString("CMD_Messages_RefreshMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Selected to OFAC Check.
        /// </summary>
        internal static string CMD_Messages_Release {
            get {
                return ResourceManager.GetString("CMD_Messages_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string CMD_Messages_Update {
            get {
                return ResourceManager.GetString("CMD_Messages_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string GV_COL_Messages_Approve {
            get {
                return ResourceManager.GetString("GV_COL_Messages_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Message.
        /// </summary>
        internal static string GV_COL_Messages_AuditMessage {
            get {
                return ResourceManager.GetString("GV_COL_Messages_AuditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Status.
        /// </summary>
        internal static string GV_COL_Messages_AuditStatus {
            get {
                return ResourceManager.GetString("GV_COL_Messages_AuditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Char.
        /// </summary>
        internal static string GV_COl_Messages_ChineseChar {
            get {
                return ResourceManager.GetString("GV_COl_Messages_ChineseChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string GV_COL_Messages_CreateDate {
            get {
                return ResourceManager.GetString("GV_COL_Messages_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTC Code.
        /// </summary>
        internal static string GV_COl_Messages_CTCCode {
            get {
                return ResourceManager.GetString("GV_COl_Messages_CTCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string GV_COL_Messages_ID {
            get {
                return ResourceManager.GetString("GV_COL_Messages_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string GV_COl_Messages_Label {
            get {
                return ResourceManager.GetString("GV_COl_Messages_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string GV_COL_Messages_Level {
            get {
                return ResourceManager.GetString("GV_COL_Messages_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string GV_COL_Messages_ModifiedDate {
            get {
                return ResourceManager.GetString("GV_COL_Messages_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trans.
        /// </summary>
        internal static string GV_COl_Messages_NewTrans {
            get {
                return ResourceManager.GetString("GV_COl_Messages_NewTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFAC Violation.
        /// </summary>
        internal static string GV_COL_Messages_OFACViolation {
            get {
                return ResourceManager.GetString("GV_COL_Messages_OFACViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Trans.
        /// </summary>
        internal static string GV_COl_Messages_OldTrans {
            get {
                return ResourceManager.GetString("GV_COl_Messages_OldTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Message.
        /// </summary>
        internal static string GV_COL_Messages_OriginalMessage {
            get {
                return ResourceManager.GetString("GV_COL_Messages_OriginalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Message.
        /// </summary>
        internal static string GV_COL_Messages_ResponseMessage {
            get {
                return ResourceManager.GetString("GV_COL_Messages_ResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string GV_COL_Messages_Review {
            get {
                return ResourceManager.GetString("GV_COL_Messages_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string GV_COL_Messages_Select {
            get {
                return ResourceManager.GetString("GV_COL_Messages_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string GV_COL_Messages_Status {
            get {
                return ResourceManager.GetString("GV_COL_Messages_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Message.
        /// </summary>
        internal static string GV_COL_Messages_TranslatedMessage {
            get {
                return ResourceManager.GetString("GV_COL_Messages_TranslatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string GV_COl_Messages_Value {
            get {
                return ResourceManager.GetString("GV_COl_Messages_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Details.
        /// </summary>
        internal static string LBL_Messages_AuditDetails {
            get {
                return ResourceManager.GetString("LBL_Messages_AuditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Messages created between %1 and %2 and status is %3, Auto refresh is turned %4..
        /// </summary>
        internal static string LBL_Messages_DisplayMessages {
            get {
                return ResourceManager.GetString("LBL_Messages_DisplayMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Create Date:.
        /// </summary>
        internal static string LBL_Messages_FromCreateDate {
            get {
                return ResourceManager.GetString("LBL_Messages_FromCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaasge Text:.
        /// </summary>
        internal static string LBL_Messages_MeaasgeText {
            get {
                return ResourceManager.GetString("LBL_Messages_MeaasgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Details.
        /// </summary>
        internal static string LBL_Messages_OriginalDetails {
            get {
                return ResourceManager.GetString("LBL_Messages_OriginalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria:.
        /// </summary>
        internal static string LBL_Messages_SearchCriteria {
            get {
                return ResourceManager.GetString("LBL_Messages_SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string LBL_Messages_Status {
            get {
                return ResourceManager.GetString("LBL_Messages_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Create Date:.
        /// </summary>
        internal static string LBL_Messages_ToCreateDate {
            get {
                return ResourceManager.GetString("LBL_Messages_ToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select a day before then From Date!.
        /// </summary>
        internal static string MSG_DateCannotBeforeThenFromDate {
            get {
                return ResourceManager.GetString("MSG_DateCannotBeforeThenFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select a day later then To date!.
        /// </summary>
        internal static string MSG_DateCannotLaterThenToDate {
            get {
                return ResourceManager.GetString("MSG_DateCannotLaterThenToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select a day later then today!.
        /// </summary>
        internal static string MSG_DateCannotLaterThenToday {
            get {
                return ResourceManager.GetString("MSG_DateCannotLaterThenToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date should not be empty!.
        /// </summary>
        internal static string MSG_FromDateNotEmpty {
            get {
                return ResourceManager.GetString("MSG_FromDateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status should not be empty!.
        /// </summary>
        internal static string MSG_StatusNotEmpty {
            get {
                return ResourceManager.GetString("MSG_StatusNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date should not be empty!.
        /// </summary>
        internal static string MSG_ToDateNotEmpty {
            get {
                return ResourceManager.GetString("MSG_ToDateNotEmpty", resourceCulture);
            }
        }
    }
}
