//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telavance.AdvantageSuite.Wei.WeiService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InterfaceStatus", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public partial class InterfaceStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int InterfaceIdField;

        private string InterfaceNameField;

        private Telavance.AdvantageSuite.Wei.WeiService.DriverStatus StatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterfaceId
        {
            get
            {
                return this.InterfaceIdField;
            }
            set
            {
                this.InterfaceIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterfaceName
        {
            get
            {
                return this.InterfaceNameField;
            }
            set
            {
                this.InterfaceNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Telavance.AdvantageSuite.Wei.WeiService.DriverStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DriverStatus", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public enum DriverStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotRunning = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Starting = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shuttingdown = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 5,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Request", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime CreateDateField;

        private string CreateOperField;

        private bool HasCTCField;

        private string HeaderField;

        private int InterfaceIdField;

        private bool IsErrorField;

        private string MessageBodyField;

        private System.DateTime ModifiedDateField;

        private string NameField;

        private Telavance.AdvantageSuite.Wei.WeiService.OfacStatus OfacStatusField;

        private int RequestIdField;

        private string ResponseMessageField;

        private Telavance.AdvantageSuite.Wei.WeiService.Status StatusField;

        private string TranslatedMessageField;

        private bool hasCTCApprovedField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateOper
        {
            get
            {
                return this.CreateOperField;
            }
            set
            {
                this.CreateOperField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasCTC
        {
            get
            {
                return this.HasCTCField;
            }
            set
            {
                this.HasCTCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InterfaceId
        {
            get
            {
                return this.InterfaceIdField;
            }
            set
            {
                this.InterfaceIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Telavance.AdvantageSuite.Wei.WeiService.OfacStatus OfacStatus
        {
            get
            {
                return this.OfacStatusField;
            }
            set
            {
                this.OfacStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Telavance.AdvantageSuite.Wei.WeiService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslatedMessage
        {
            get
            {
                return this.TranslatedMessageField;
            }
            set
            {
                this.TranslatedMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hasCTCApproved
        {
            get
            {
                return this.hasCTCApprovedField;
            }
            set
            {
                this.hasCTCApprovedField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OfacStatus", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public enum OfacStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirm = 3,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Status", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public enum Status : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unprocessed = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Translated = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Review = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentForOfacCheck = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfacResponseReceived = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processed = 6,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuditMessages", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiService")]
    public partial class AuditMessages : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Telavance.AdvantageSuite.Wei.WeiCommon.AuditLevel auditLevelField;

        private System.DateTime createdDateField;

        private string messageField;

        private Telavance.AdvantageSuite.Wei.WeiService.Status statusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Telavance.AdvantageSuite.Wei.WeiCommon.AuditLevel auditLevel
        {
            get
            {
                return this.auditLevelField;
            }
            set
            {
                this.auditLevelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Telavance.AdvantageSuite.Wei.WeiService.Status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
}
namespace Telavance.AdvantageSuite.Wei.WeiCommon
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuditLevel", Namespace = "http://schemas.datacontract.org/2004/07/Telavance.AdvantageSuite.Wei.WeiCommon")]
    public enum AuditLevel : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWeiMonitoring")]
public interface IWeiMonitoring
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/forceShutdown", ReplyAction = "http://tempuri.org/IWeiMonitoring/forceShutdownResponse")]
    bool forceShutdown();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/ShutdownGracefully", ReplyAction = "http://tempuri.org/IWeiMonitoring/ShutdownGracefullyResponse")]
    bool ShutdownGracefully();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/getInterfaces", ReplyAction = "http://tempuri.org/IWeiMonitoring/getInterfacesResponse")]
    Telavance.AdvantageSuite.Wei.WeiService.InterfaceStatus[] getInterfaces();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/getStatistics", ReplyAction = "http://tempuri.org/IWeiMonitoring/getStatisticsResponse")]
    string getStatistics(int interfaceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/getAllErrors", ReplyAction = "http://tempuri.org/IWeiMonitoring/getAllErrorsResponse")]
    Telavance.AdvantageSuite.Wei.WeiService.Request[] getAllErrors(int interfaceId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/getAuditMessages", ReplyAction = "http://tempuri.org/IWeiMonitoring/getAuditMessagesResponse")]
    Telavance.AdvantageSuite.Wei.WeiService.AuditMessages[] getAuditMessages(int requestId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/reprocess", ReplyAction = "http://tempuri.org/IWeiMonitoring/reprocessResponse")]
    void reprocess(int requestId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWeiMonitoring/processMessageForOFACCheck", ReplyAction = "http://tempuri.org/IWeiMonitoring/processMessageForOFACCheckResponse")]
    bool processMessageForOFACCheck(int requestId, bool fromErrorQueue);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWeiMonitoringChannel : IWeiMonitoring, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WeiMonitoringClient : System.ServiceModel.ClientBase<IWeiMonitoring>, IWeiMonitoring
{

    public WeiMonitoringClient()
    {
    }

    public WeiMonitoringClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public WeiMonitoringClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WeiMonitoringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WeiMonitoringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public bool forceShutdown()
    {
        return base.Channel.forceShutdown();
    }

    public bool ShutdownGracefully()
    {
        return base.Channel.ShutdownGracefully();
    }

    public Telavance.AdvantageSuite.Wei.WeiService.InterfaceStatus[] getInterfaces()
    {
        return base.Channel.getInterfaces();
    }

    public string getStatistics(int interfaceId)
    {
        return base.Channel.getStatistics(interfaceId);
    }

    public Telavance.AdvantageSuite.Wei.WeiService.Request[] getAllErrors(int interfaceId)
    {
        return base.Channel.getAllErrors(interfaceId);
    }

    public Telavance.AdvantageSuite.Wei.WeiService.AuditMessages[] getAuditMessages(int requestId)
    {
        return base.Channel.getAuditMessages(requestId);
    }

    public void reprocess(int requestId)
    {
        base.Channel.reprocess(requestId);
    }

    public bool processMessageForOFACCheck(int requestId, bool fromErrorQueue)
    {
        return base.Channel.processMessageForOFACCheck(requestId, fromErrorQueue);
    }
}
